name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install sbcl
      run: sudo apt install sbcl
    - name: Install quicklisp
      run: curl -O https://beta.quicklisp.org/quicklisp.lisp && echo '(load "quicklisp.lisp")(quicklisp-quickstart:install)(ql:add-to-init-file)' > install.lisp && sbcl --load quicklisp.lisp --script install.lisp

