name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install sbcl
      run: sudo apt install sbcl
    - name: Install quicklisp && TEST
      run: |
        curl -O https://beta.quicklisp.org/quicklisp.lisp
        echo '(load "quicklisp.lisp")(quicklisp-quickstart:install)' > install.lisp
        echo '(ql:quickload :rove)(rove:run :pippet/tests)' > test.lisp
        sbcl --load quicklisp.lisp --script install.lisp
        cp -r /home/runner/work/pippet/pippet ~/quicklisp/local-projects
        sbcl --script test.lisp
