name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install sbcl
      run: sudo apt install sbcl
    - name: Install quicklisp
      run: curl -O https://beta.quicklisp.org/quicklisp.lisp && echo '(load "quicklisp.lisp")(quicklisp-quickstart:install)' > install.lisp && sbcl --load quicklisp.lisp --script install.lisp &&
        echo '(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp"
                                         (user-homedir-pathname))))
                (when (probe-file quicklisp-init)
              (load quicklisp-init)))' > ~/.sbclrc
    - name: Run Test
      run: cp -r pippet ~/quicklisp/local-projects && echo "(ql:quickload :rove)(rove:run :pippet/tests)" > test.lisp && sbcl --script test.lisp

